name: Reusable for Image build/push

on:
  workflow_call:
    inputs:
      initial:
        type: string
        required: false
        default: 'no'
      app-component:
        type: string 
        required: true
      container:
        type: string
        required: true
      port:
        type: string
        required: true
        

jobs:
  Image_build-push:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.tagging.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build and tag of docker image
        id: tagging
        run: |
          if ${{ inputs.initial  == 'yes' }}; then
            echo IMAGE_TAG=first >> $GITHUB_OUTPUT
          else  
            echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi 
          docker build -t ${{secrets.DOCKER_UNAME}}/${{inputs.app-component}}:${{outputs.image-tag}} .


          
      - name: Test newly created build image
        run: docker run --rm -d --name ${{container}} -p ${{inputs.port}}:${{inputs.port}} ${{secrets.DOCKER_UNAME}}/${{inputs.app-component}}:${{outputs.image-tag}}
      - name: Push image to DockerHub
        if  : success()
        run : |
          docker login -u ${{ secrets.DOCKER_UNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${{ secrets.DOCKER_UNAME }}/${{inputs.app-component}}:${{ outputs.image-tag }}
