name: Reusable for Image build/push

on:
  workflow_call:
    inputs:
      initial:
        type: string
        required: false
        default: 'no'
      app-component:
        type: string 
        required: true
      container:
        type: string
        required: true
      port:
        type: string
        required: true
    secrets:
      docker-uname:
        required: true
      docker-token:
        required: true
    
jobs:
  Image_build-push:
    runs-on: ubuntu-latest

    #outputs:
      #image-tag: ${{ steps.tagging.outputs.IMAGE_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Docker Username.
        run: echo "Docker username is '${{ secrets.docker-uname }}'"

        
      - name: Build and tag of docker image
        id: tagging
        run: |
          if [[ "${{ inputs.initial }}" == "yes" ]]; then
            IMAGE_TAG="first"
          else  
            IMAGE_TAG="${GITHUB_SHA::7}"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Image Tag: $IMAGE_TAG"  # Debugging output
          docker build -t ${{ secrets.docker-uname }}/${{ inputs.app-component }}:$IMAGE_TAG .

          
      - name: Test newly created build image
        run: docker run --rm -d --name ${{inputs.container}} -p ${{inputs.port}}:${{inputs.port}} ${{secrets.docker-uname}}/${{inputs.app-component}}:$IMAGE_TAG
      - name: Push image to DockerHub
        if  : success()
        run : |
          docker login -u ${{ secrets.docker-uname }} -p ${{ secrets.docker-token }}
          docker push ${{ secrets.docker-uname }}/${{inputs.app-component}}:$IMAGE_TAG
